# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_issueance_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequest',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EquipmentInstance'),
        ),
    ]
