# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_auto_20171008_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='issuerq',
            field=models.ManyToManyField(blank=True, through='main.IssueRequest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='issuerequest',
            unique_together=set([('equipment', 'user')]),
        ),
    ]
