# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20171012_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Equipment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issuerequest',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='issuerequest',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='issuerequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='issuerq',
        ),
        migrations.AlterField(
            model_name='equipmentinstance',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eqins', to='main.Equipment'),
        ),
        migrations.DeleteModel(
            name='IssueRequest',
        ),
        migrations.AddField(
            model_name='equipment',
            name='followers',
            field=models.ManyToManyField(blank=True, through='main.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together=set([('equipment', 'user')]),
        ),
    ]
